# 由 tools/generate-contracts/generate.py 生成；禁止手工编辑。
# 契约主版本: 1；源哈希: 3578f82330fbba2e9e500f67fd1b574296707f5b20058cae9d70ed9bc3868ce5
from __future__ import annotations

from typing import Mapping, Protocol

JsonObject = Mapping[str, object]

class ApiClient(Protocol):
    def approveModelDeployment(self, request: JsonObject | None = None) -> JsonObject: ...
    def claimReviewTask(self, request: JsonObject | None = None) -> JsonObject: ...
    def completeCaptureImage(self, request: JsonObject | None = None) -> JsonObject: ...
    def completeReviewAnnotation(self, request: JsonObject | None = None) -> JsonObject: ...
    def createAnnotationUploadTicket(self, request: JsonObject | None = None) -> JsonObject: ...
    def createCapture(self, request: JsonObject | None = None) -> JsonObject: ...
    def createDatasetVersion(self, request: JsonObject | None = None) -> JsonObject: ...
    def createImageAccessTicket(self, request: JsonObject | None = None) -> JsonObject: ...
    def createModelDeployment(self, request: JsonObject | None = None) -> JsonObject: ...
    def createTrainingRun(self, request: JsonObject | None = None) -> JsonObject: ...
    def getDatasetVersion(self, request: JsonObject | None = None) -> JsonObject: ...
    def getDetection(self, request: JsonObject | None = None) -> JsonObject: ...
    def getEdgeCapture(self, request: JsonObject | None = None) -> JsonObject: ...
    def getInferenceReadiness(self, request: JsonObject | None = None) -> JsonObject: ...
    def getReviewWorkspace(self, request: JsonObject | None = None) -> JsonObject: ...
    def getTrainingRun(self, request: JsonObject | None = None) -> JsonObject: ...
    def listDetections(self, request: JsonObject | None = None) -> JsonObject: ...
    def listReviewTasks(self, request: JsonObject | None = None) -> JsonObject: ...
    def listRuntimeModels(self, request: JsonObject | None = None) -> JsonObject: ...
    def queryCaptureSync(self, request: JsonObject | None = None) -> JsonObject: ...
    def releaseReviewTask(self, request: JsonObject | None = None) -> JsonObject: ...
    def renewCaptureImageUploadTicket(self, request: JsonObject | None = None) -> JsonObject: ...
    def reportDeviceHeartbeat(self, request: JsonObject | None = None) -> JsonObject: ...
    def retryDetection(self, request: JsonObject | None = None) -> JsonObject: ...
    def rollbackModelDeployment(self, request: JsonObject | None = None) -> JsonObject: ...
    def startDetectionAttempt(self, request: JsonObject | None = None) -> JsonObject: ...
    def streamAuthorizedEvents(self, request: JsonObject | None = None) -> JsonObject: ...
    def submitCapture(self, request: JsonObject | None = None) -> JsonObject: ...
    def submitDetectionFailure(self, request: JsonObject | None = None) -> JsonObject: ...
    def submitDetectionResult(self, request: JsonObject | None = None) -> JsonObject: ...
    def submitModelValidationDecision(self, request: JsonObject | None = None) -> JsonObject: ...
    def submitReview(self, request: JsonObject | None = None) -> JsonObject: ...
