# 由 tools/generate-contracts/generate.py 生成；禁止手工编辑。
# 契约主版本: 2；源哈希: ff943178ec32e8d1e936321170d1a28f70eab0edcd15a37884c81f148abb5ad4
from typing import Mapping, Protocol

JsonObject = Mapping[str, object]

class ApiClientV2(Protocol):
    def addDetectionBatchItemV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def approveModelActivationRequestV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def completeDetectionBatchItemUploadV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def completeModelUploadSessionV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createAdminFeedbackV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createDetectionBatchV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createModelActivationRequestV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createModelRollbackRequestV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createModelUploadSessionV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createProductionDetectionItemV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createSampleCandidateV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createSampleExportDownloadTicketV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createSampleExportV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def createSampleExternalReceiptV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def decideSampleCandidateV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def deleteDetectionBatchItemV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def getDetectionBatchItemV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def getDetectionBatchV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def getManualDetectionCapabilitiesV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def getModelUploadSessionV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def getSampleExportV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def listAdminDetectionItemsV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def listDetectionBatchesV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def listModelVersionsV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def listSampleCandidatesV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def putQuickReviewV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def renewDetectionBatchItemUploadV2(self, request: JsonObject | None = None) -> JsonObject: ...
    def submitDetectionBatchV2(self, request: JsonObject | None = None) -> JsonObject: ...
