/**
 * 前端对冻结契约生成包的唯一入口。
 *
 * 网络对象和状态类型均从 `contracts/` 生成，手写请求层只负责认证、重试、
 * 请求标识与错误转换，不复制领域枚举。
 */
export {
  CONTRACT_MAJOR_VERSION,
  CONTRACT_SOURCE_SHA256,
} from '@contracts/index'

export type {
  Acknowledgement,
  AlgorithmOutcome,
  ApprovalRequest,
  AttemptStatus,
  AuditRecordPage,
  AuditRecordSummary,
  AsyncAccepted,
  BusinessDisposition,
  CaptureStatusResponse,
  CaptureStatus,
  DatasetCreateRequest,
  DatasetApprovalRequest,
  DatasetCandidateManifestApprovalResponse,
  DatasetCandidateManifestPage,
  DatasetCandidateManifestSummary,
  DatasetPage,
  DatasetSummary,
  DatasetVersionApprovalResponse,
  DatasetVersionCreateRequest,
  DatasetVersionDiff,
  DatasetVersionDiffItem,
  DatasetVersionPage,
  DatasetVersionSummary,
  DetectionDetail,
  DetectionPage,
  DetectionSummary,
  ExecutionStatus,
  ImageAccessTicketResponse,
  ImageReference,
  ImageKind,
  LocalQueueStatus,
  ModelCreateRequest,
  ModelDeploymentCreateRequest,
  ModelDeploymentPage,
  ModelDeploymentResponse,
  ModelDeploymentSummary,
  ModelPage,
  ModelStatus,
  ModelSummary,
  ModelVersionPage,
  ModelVersionRegisterRequest,
  ModelVersionRegistrationResponse,
  ModelVersionResponse,
  ModelVersionSummary,
  ObjectCompleteResponse,
  ObjectReference,
  ObjectState,
  OverviewCaptureCounts,
  OverviewFleetHealth,
  OverviewInferenceHealth,
  OverviewModelRuntime,
  OverviewOutcomeComparison,
  OverviewOutcomeCounts,
  OverviewProductionModel,
  OverviewQualityComparison,
  OverviewQualityCounts,
  OverviewReviewBacklog,
  OverviewWindow,
  PreprocessQualityStatus,
  QualityMetricReason,
  QualityMetrics,
  ReviewStatus,
  ReviewSubmissionRequest,
  ReviewSubmissionResponse,
  ReviewTask,
  ReviewTaskPage,
  ReviewWorkspace,
  RollbackRequest,
  TrainingRunPage,
  TrainingRunCreateRequest,
  TrainingRunSummary,
  SystemOverview,
  UploadTicketResponse,
  UtcTimestamp,
  Uuid,
  ValidationDecisionRequest,
  Version,
  VersionedResource,
} from '@contracts/index'

export type {
  AlgorithmOutcome as AlgorithmOutcomeV2,
  BatchAggregateCounts,
  BatchItemStatus,
  BatchSource,
  BatchStatus,
  DetectionBatch,
  DetectionBatchItem,
  ImageQualityResult,
  QuickReviewDecision,
  QuickReviewRecord,
  UsageStage,
} from '@contracts/v2/index'

export type {
  ApiClient as GeneratedApiClient,
  JsonObject,
} from '@contracts/client'

export type { ApiClientV2 as GeneratedApiClientV2 } from '@contracts/v2/client'
